uavcan.node.id:
  type: Integer
  note: Defines a node-ID. Allowed values [0,127].
  enum: PARAM_UAVCAN_NODE_ID
  flags: mutable
  default: 42
  min: 0
  max: 255

system.name:
  type: String
  note: Defines custom node name. If empty, the node will use the default name.
  enum: PARAM_SYSTEM_NAME
  flags: mutable
  default: "co.raccoonlab.mini"

led_pull_down.ttl_cmd:
  type: Integer
  note: Defines the time to live for the command in milliseconds.
  enum: PARAM_LED_PULL_DOWN_TTL_CMD
  flags: mutable
  default: 1000
  min: 0
  max: 10000

led_pull_down.pwm_cmd_type:
  type: Integer
  note: Defines the type of the command.
  enum: PARAM_LED_PULL_DOWN_PWM_CMD_TYPE
  flags: mutable
  default: 0
  min: 0
  max: 1

led_pull_down.switch_channel:
  type: Integer
  note: Index of switch channel. [-1; 255]. -1 means disabled.
  enum: PARAM_LED_PULL_DOWN_SWITCH_CHANNEL
  flags: mutable
  default: -1
  min: -2
  max: 255

led_pull_down.position_channel:
  type: Integer
  note: Index of position channel[-1; 255]. If switch channel is disabled, the position channel is ignored. -1 means disabled.
  enum: PARAM_LED_PULL_DOWN_POSITION_CHANNEL
  flags: mutable
  default: -1
  min: -2
  max: 255
