fuel.empty_tank_enc_raw:
  type: Integer
  note: Defines raw sensor value that corresponds to the empty fuel tank.
  enum: PARAM_FUEL_TANK_EMPTY
  flags: mutable
  default: 0
  min: 0
  max: 5000

fuel.full_tank_enc_raw:
  type: Integer
  note: Defines raw sensor value that corresponds to the full fuel tank.
  enum: PARAM_FUEL_TANK_FULL
  flags: mutable
  default: 0
  min: 0
  max: 5000

fuel.volume:
  type: Integer
  note: Defines a volume of the fuel tank [cm3].
  enum: PARAM_FUEL_TANK_VOLUME
  flags: mutable
  default: 5000
  min: 0
  max: 65535

fuel.min_magnitude:
  type: Integer
  note: The minimal required magnitude.
  enum: PARAM_FUEL_TANK_MIN_MAGNITUDE
  flags: mutable
  default: 5
  min: 0
  max: 255

fuel.tank_id:
  type: Integer
  note: Defines an id of the fuel tank.
  enum: PARAM_FUEL_TANK_ID
  flags: mutable
  default: 0
  min: 0
  max: 255

fuel.ptc_step_1:
  type: Integer
  note: Defines ptc of the fuel tank for step 1.
  enum: PARAM_FUEL_TANK_STEP_1
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_2:
  type: Integer
  note: Defines ptc of the fuel tank for step 2.
  enum: PARAM_FUEL_TANK_STEP_2
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_3:
  type: Integer
  note: Defines ptc of the fuel tank for step 3.
  enum: PARAM_FUEL_TANK_STEP_3
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_4:
  type: Integer
  note: Defines ptc of the fuel tank for step 4.
  enum: PARAM_FUEL_TANK_STEP_4
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_5:
  type: Integer
  note: Defines ptc of the fuel tank for step 5.
  enum: PARAM_FUEL_TANK_STEP_5
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_6:
  type: Integer
  note: Defines ptc of the fuel tank for step 6.
  enum: PARAM_FUEL_TANK_STEP_6
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_7:
  type: Integer
  note: Defines ptc of the fuel tank for step 7.
  enum: PARAM_FUEL_TANK_STEP_7
  flags: mutable
  default: 0
  min: 0
  max: 100

fuel.ptc_step_8:
  type: Integer
  note: Defines ptc of the fuel tank for step 8.
  enum: PARAM_FUEL_TANK_STEP_8
  flags: mutable
  default: 0
  min: 0
  max: 100
